name       : perl-xml-sax-expat
version    : 0.51
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/B/BJ/BJOERN/XML-SAX-Expat-0.51.tar.gz : 4c016213d0ce7db2c494e30086b59917b302db8c292dcd21f39deebd9780c83f
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : XML::SAX::Expat - SAX2 Driver for Expat (XML::Parser)
description: |
    This is an implementation of a SAX2 driver sitting on top of Expat.
builddeps  :
    - perl-test-pod-coverage
    - perl-test-pod
    - perl-xml-namespacesupport
    - perl-xmlparser
    - perl-xml-sax
    - perl-xml-saxbase
rundeps    :
    - perl-xml-namespacesupport
    - perl-xmlparser
    - perl-xml-sax
    - perl-xml-saxbase
setup      : |
    export 'SKIP_SAX_INSTALL=1'
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    install -D -m 00644 $pkgfiles/ParserDetails.ini $installdir/usr/lib64/perl5/vendor_perl/5.28/XML/
check      : |
    %perl_build test
